apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo 
  namespace: roboshop
spec:
  replicas: 4
  selector:
    matchLabels:
     purpose: checking 
  template:
    metadata:
      labels:
        purpose: checking 
    spec:
      containers:
        - name: nginx
          image: nginx

---
apiVersion: v1 
kind: Service
metadata:
  name: pv-demo
  namespace: roboshop
spec:
  selector:
    purpose: checking 
  ports:
    - port: 80
      targetPort: 80

